export const requiredFields = {
  basicInfo: [
    "name",
    "race",
    "class",
    "level",
    "alignment",
    "background",
    "playerName",
  ],
  abilities: [
    "strength",
    "dexterity",
    "constitution",
    "intelligence",
    "wisdom",
    "charisma",
  ],
  stats: [
    "initiative",
    "speed",
    "armorClass",
    "hitPointsCurrent",
    "hitPointsTotal",
    "hitDice",
  ],
  savingThrows: [
    "strength",
    "dexterity",
    "constitution",
    "intelligence",
    "wisdom",
    "charisma",
  ],
  skills: [
    "acrobatics",
    "animalHandling",
    "arcana",
    "athletics",
    "deception",
    "history",
    "insight",
    "intimidation",
    "investigation",
    "medicine",
    "nature",
    "perception",
    "performance",
    "persuasion",
    "religion",
    "sleightOfHand",
    "stealth",
    "survival",
  ],
};
